# Generated by Django 5.1.3 on 2024-11-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_product_image_orderitem_delete_itemorder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="date_orderd",
            new_name="date_ordered",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(default="default@example.com", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.order"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="digital",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="Unknown", max_length=200),
            preserve_default=False,
        ),
    ]
