# Generated by Django 5.1.3 on 2024-11-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
