# Generated by Django 5.1.3 on 2024-11-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_remove_profile_email_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="organization_name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
