# Generated by Django 5.1.3 on 2024-11-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_profile_phone_number_alter_profile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, default="Unknown", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="organization_name",
            field=models.CharField(blank=True, default="Unknown", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, default="Unknown", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
