# Generated by Django 5.1.3 on 2024-11-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_profile_email_alter_profile_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/profile_pics/"
            ),
        ),
    ]
