# Generated by Django 5.1.3 on 2024-11-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_remove_profile_email_alter_profile_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="images/default.png", upload_to="images/profile_pics/"
            ),
        ),
    ]
