# Generated by Django 5.1.3 on 2024-11-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_remove_profile_address_remove_profile_birthday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
