# Generated by Django 5.1.3 on 2024-11-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_profile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
