# Generated by Django 5.1.3 on 2024-11-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_profile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
